#pragma once

#include "http.h"

enum ParsingState {
  PARSING_BEGIN,
  PARSING_METHOD,
  PARSING_RESOURCE_BEGIN,
  PARSING_RESOURCE,
  PARSING_PARAMS_BEGIN,
  PARSING_PARAMS_NAME,
  PARSING_PARAMS_VALUE,

  PARSING_VERSION_H,
  PARSING_VERSION_HT,
  PARSING_VERSION_HTT,
  PARSING_VERSION_HTTP,
  PARSING_VERSION_HTTPS,

  PARSING_VERSION_MAJOR,
  PARSING_VERSION_MAJOR_LONG,

  PARSING_VERSION_MINOR,
  PARSING_VERSION_MINOR_LONG,

  PARSING_NEW_LINE,

  PARSING_HEADER_BEGIN,
  PARSING_HEADER_NAME,
  PARSING_HEADER_SEPERATOR,
  PARSING_HEADER_SKIP,
  PARSING_HEADER_VALUE,
  PARSING_HEADER_END,

  PARSING_BODY_BEGIN,
  PARSING_BODY,

};

bool parseHttpRequest(char *, HTTPRequest &);

std::string decodeURIComponent(std::string);